---
title: "Generate Eigen gene QTL"
output: html_notebook
---

What are the QTL for eigen genes?

Eigen genes were computed from WGCNA clusters. I am taking the top eigen genes that were correlated with growth model traits and determining eQTL for these.

This script is to get the QTL.  A separte script will be used to analyze the QTL.

```{r}
library(tidyverse)
library(qtl)
library(stringr)
library(snowfall)
```

## get cross ingo

### get eigen genes and format for qtl

```{r}
eigen.UN <- read_csv("../output/Sig_Eigen_genes_UN_2012.csv")
colnames(eigen.UN)[-1] <- str_c("UN_",colnames(eigen.UN)[-1])

eigen.UN.t <- eigen.UN %>%
  select(-X1) %>%
  t() %>%
  as_tibble %>%
  mutate(id=colnames(eigen.UN)[-1]) %>%
  select(id,everything())

colnames(eigen.UN.t)[-1] <- eigen.UN$X1

eigen.UN.t
```

```{r}
write_csv(eigen.UN.t,"../output/Top_Eigen_genes_qtl_input_2012.csv")
```


### 

```{r}
cross.all <- read.cross("csvsr", 
                       genfile="../input/snp_map_rqtl_Mbp_ref1.5.2_cross_output_gen.csv" , 
	                       phefile="../output/Top_Eigen_genes_qtl_input.csv", 
	                       genotypes=c("AA","BB"), na.strings = "-")

class(cross.all)[1] <- "riself"
cross.all <- jittermap(cross.all)
cross.all
```

```{r}
cross.all <- est.rf(cross.all)
plotRF(cross.all) 

cross.all <- calc.errorlod(cross.all, error.prob=0.001)
cross.all <- sim.geno(cross.all,step=2)
```


```{r}
system.time(scanone_eigen <- scanone(cross.all, pheno.col = 2:ncol(cross.all$pheno), 
	         method = "imp", use = "all.obs"))
scanone_eigen_cim <- lapply(2:ncol(cross.all$pheno),function(pheno) cim(cross.all, pheno.col = pheno, 
	         method = "imp"))

scanone_eigen_cim <- do.call(c,scanone_eigen_cim)
colnames(scanone_eigen_cim)[-1:-2] <- colnames(cross.all$pheno)[-1]

```

```{r}

#the built-in parallel method for scanone is hanging, so roll my own
sfInit(parallel = TRUE, cpus = 4)

sfLibrary(qtl)

sfExport("cross.all")

set.seed(12345)
system.time(permtest <- sfLapply(1:4,function(x) scanone(cross.all, method = "imp", 
                       pheno.col = 2:ncol(cross.all$pheno),
                       n.perm = 250)))

sfStop()

permtest <- do.call(rbind,permtest)

attr(permtest,"method") <- "imp"
attr(permtest,"model") <- "normal"
attr(permtest,"type") <- "riself"
attr(permtest,"class") <- c("scanoneperm","matrix")

permtest[1:5,1:5]

dim(permtest)

```

```{r}
sfInit(parallel = TRUE, cpus = 4)

sfLibrary(qtl)

sfExport("cross.all")

system.time(permtest.cim <- sfSapply(2:ncol(cross.all$pheno),
                                     function(pheno) cim(cross.all,
                                                         pheno.col = pheno, 
                                                         method = "imp",
                                                         n.perm=1000))
)

sfStop()

attr(permtest.cim,"class") <- "scanoneperm"

colnames(permtest.cim) <- colnames(cross.all$pheno)[-1]
```


```{r}
alphas <- seq(0.01, 0.10, by = 0.01)
lod.thrs <- summary(permtest, alphas)
lod.thrs
```

```{r}
lod.thrs.cim <- summary(permtest.cim, alphas)
lod.thrs.cim
```


```{r}
save(cross.all,scanone_eigen,scanone_eigen_cim,permtest,permtest.cim,lod.thrs,lod.thrs.cim,file = "../output/scanone-eigengene-qtl_2012.RData")
```
